In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [2]:
female_business_owner = pd.read_csv('../data/female_business_owner_data.csv', engine='python')
female_business_owner.shape

(379, 18)

In [3]:
female_business_owner.head()

,Country,Income group,Year,Number of female business owners of new LLCs,Number of male business owners of new LLCs,Total number of business owners of new LLCs,Number of female sole proprietors,Number of male sole proprietors,Total number of sole proprietors,Number of female directors of new LCCS,Number of male directors of new LCCS,Total number of directors of new LCCS,Share of female business owners of new LLCs,Share of male business owners of new LLCs,Share of female sole proprietors,Share of male sole proprietors,Share of female directors of new LCCs,Share of male directors of new LCCs
0,Afghanistan,Low income,2014.0,65,"5,043","5,108",14,"2,117","2,131",34,"3,414","3,448",1.3%,98.7%,0.7%,99.3%,1.0%,99.0%
1,Afghanistan,Low income,2015.0,45,"4,704","4,749",26,"3,110","3,136",11,"2,398","2,409",0.9%,99.1%,0.8%,99.2%,0.5%,99.5%
2,Afghanistan,Low income,2016.0,65,"5,036","5,101",33,"4,403","4,436",32,"2,473","2,505",1.3%,98.7%,0.7%,99.3%,1.3%,98.7%
3,Afghanistan,Low income,2017.0,88,"6,047","6,135",74,"4,343","4,417",34,"2,677","2,711",1.4%,98.6%,1.7%,98.3%,1.3%,98.7%
4,Afghanistan,Low income,2018.0,177,"8,482","8,659",149,"5,103","5,252",93,"5,057","5,150",2.0%,98.0%,2.8%,97.2%,1.8%,98.2%